--
-- Author: Your Name
-- Date: 2014-08-11 17:19:58
--
describe["主菜单侧边栏测试"] = function ()
  before = function()
    printInfo('before')
  end

  after = function()
    printInfo('after')
  end

  local main_menu_page
  local hero_dialog

    it["打开侧边栏"] = function(done)
  	    Promise()
  		:delay(1)
  		:and_then(function()
  		main_menu_page = app:getNavigationController():getTopPage()
  		main_menu_page._scaling:_onTouch({name ="began"})
  	end)
  	:delay(1)
  	:and_then(capture)
  	:and_then(function()
  		done()
  	end)
  	:done()
  	end
    it["打开英雄界面"] = function(done)
		Promise()
		:delay(1)
		:and_then(function()
			hero_dialog = main_menu_page._scaling:_onButtondownSideMenuHero()
		end)
		:delay(1)
		:and_then(function()
			expect(hero_dialog).should_be(app:getNavigationController():getTopDialog())
			done()
		end)
		:done()
	end
	it["右边tab栏切换"] = function(done)
		Promise()
		:delay(1)
		:and_then(function()
			hero_dialog:_onTriggerMagicAttack()
		end)
		:delay(1)
		:and_then(capture)
		:and_then(function()
			hero_dialog:_onTriggerTabContentAttack()
		end)
		:delay(1)
		:and_then(capture)
		:and_then(function()
			hero_dialog:_onTriggerTabTreatment()
		end)
		:delay(1)
		:and_then(capture)
		:and_then(function()
			hero_dialog:_onTriggerTabTank()
		end)
		:delay(1)
    :and_then(capture)
    :and_then(function()
      hero_dialog = app:getNavigationController():getTopDialog()
      hero_dialog:_onTriggerTabAll()
    end)
		:delay(1)
		:and_then(capture)
		:and_then(function()
			done()
		end)
		:done()
	end
	 it["英雄信息页面"] = function(done)
	 	local hero_Information_dialog
	 	Promise()
	 	:delay(1)
	 	:and_then(function()
	 	   hero_dialog = app:getNavigationController():getTopDialog()
	 		 local herosFrame = hero_dialog._page:getHeroFrames()
	 		 herosFrame[#herosFrame]:_onTriggerHeroOverview()
	 		-- hero_Information_dialog = hero_dialog:onEvent({["hero"] = {["actorId"] = "human_wrath",["breakthrough"] = 0,["exp"] = 0,["force"] = 0,["grade"] = 0,["heroId"] = "3e192445-8f80-4edb-a476-b8ecff65e1f0",["items"] = "22001",["level"] = 1,["sid"] = "1cb91768-4432-43ce-95fb-807abee86e58",["skills"] = "innate_1;phyattack_chop_1;taunt_1;shield_wall_1;charge_1",["userId"] = "b3bf2220-23f1-4df3-aad8-318d962b866f"},["name"] = "EVENT_HERO_FRAMES_CLICK",["pos"] = 1,["stop"] = function()end,["stop_"] = false})
	 	end)
	 	:delay(1)
	 	:and_then(function()	
	 		hero_Information_dialog = app:getNavigationController():getTopDialog()
	 		expect(hero_Information_dialog.class.__cname).should_be("QUIDialogheroInformation")
	 		done()
	 	end)
	 	:done()
	 end
end
