describe["测试宝箱抽卡"] = function()
    before = function()
        printInfo('before')
    end

    after = function()
        printInfo('after')
    end
    
    local main_menu_page
    local chest_dialog
    
    it["进入宝箱抽卡"] = function(done)
      Promise()
      :delay(1)
      :and_then(function()
        main_menu_page = app:getNavigationController():getTopPage()
        chest_dialog = main_menu_page:_onCheast()
      end)
      :delay(1)
      :and_then(function()
        expect(chest_dialog).should_be(app:getNavigationController():getTopDialog())
        done()
      end)
      :done()
    end
    
    it["瑟银宝箱"] = function(done)
      Promise()
      :delay(1)
      :and_then(function()
        chest_dialog:_onTriggerSilver()
      end)
      :delay(1)
      :and_then(capture)
      :and_then(function()
          done()
      end)
      :done()
    end
    
    it["返回选择宝箱"] = function(done)
       Promise()
       :delay(1)
       :and_then(function()
          chest_dialog:_backClickHandler()
       end)
       :delay(1)
       :and_then(cpature)
       :and_then(function()
          done()
       end)
       :done()
    end
    local gold_dialog
    it["选择黄金宝箱"] = function(done)
      Promise()
      :delay(1)
      :and_then(function()
        gold_dialog = chest_dialog:_onTriggerGold()
      end)
      :delay(1)
      :and_then(function()
        expect(gold_dialog).should_be(app:getNavigationController():getTopDialog())
        done()
      end)
      :done()
    end
    
    it["购买一个"] = function(done)
      Promise()
      :delay(1)
      :and_then(function()
        gold_dialog:_clickBuyOne()
      end)
      :delay(1)
      :and_then(capture)
      :and_then(function()
          done()
      end)
      :done()
    end
    
    it["返回选择购买"] = function(done)
       Promise()
       :delay(1)
       :and_then(function()
          gold_dialog:_backClickHandler()
       end)
       :delay(1)
       :and_then(cpature)
       :and_then(function()
          done()
       end)
       :done()
    end
    
--    it["购买十个"] = function(done)
--      Promise()
--      :delay(1)
--      :and_then(function()
--        gold_dialog:_clickBuyTen()
--      end)
--      :delay(1)
--      :and_then(capture)
--      :and_then(function()
--          done()
--      end)
--      :done()
--    end
    
    it["返回选择宝箱"] = function(done)
       Promise()
       :delay(1)
       :and_then(function()
          gold_dialog:_onTriggerClose()
       end)
       :delay(1)
       :and_then(cpature)
       :and_then(function()
          done()
       end)
       :done()
    end
    
    it["返回主页面"] = function(done)
       Promise()
       :delay(1)
       :and_then(function()
          chest_dialog = app:getNavigationController():getTopDialog()
          chest_dialog:_backClickHandler()
       end)
       :delay(1)
       :and_then(cpature)
       :and_then(function()
          done()
       end)
       :done()
    end
    
end